<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:i0="HP.SOAQ.SampleApp" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://tempuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" name="Flights_Service" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="HP.SOAQ.SampleApp" location="http://localhost:8000/Flights_SOAP?wsdl=wsdl0" />
  <wsdl:types />
  <wsdl:service name="Flights_Service">
    <wsdl:port name="FlightsServiceMethods" binding="i0:FlightsServiceMethods">
      <soap:address location="http://localhost:8000/Flights_SOAP" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>